# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  # --- VM 1 : MASTER (1.5 Go RAM) ---
  config.vm.define "master" do |master|
    master.vm.hostname = "k8s-master"
    master.vm.network "private_network", ip: "192.168.56.10"
    
    master.vm.provider "virtualbox" do |vb|
      vb.name = "PLM_Master"
      vb.memory = "3072"
      vb.cpus = 2
    end
  end

  # --- VM 2 : WORKER (1 Go RAM) ---
  config.vm.define "worker1" do |worker|
    worker.vm.hostname = "k8s-worker-1"
    worker.vm.network "private_network", ip: "192.168.56.11"
    
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "PLM_Worker1"
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  # Provisioning commun (Installation de Python pour Ansible)
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y python3 python3-pip
    # Désactivation du SWAP (Obligatoire pour Kubernetes plus tard)
    swapoff -a
    sed -i '/swap/d' /etc/fstab
  SHELL
end